sonar.projectKey=patorsiang_portfolio-platform-2026
sonar.projectName=Patorsiang Portfolio Platform 2026
sonar.organization=patorsiang

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/dist/**,**/build/**,**/coverage/**
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*

sonar.sourceEncoding=UTF-8

