/**
 * Records the intrinsic size of every remote image a post references, into
 * src/lib/post-image-sizes.ts.
 *
 * Run by hand when a post gains an image:
 *   bun run --cwd apps/portfolio-web post-images:manifest
 *
 * This replaced a script that downloaded the images themselves into public/.
 * The bytes now stay in `thinking-in-public` and reach the reader through
 * /_next/image; all this script still needs from them is `width` and `height`,
 * so the browser can reserve the right box and the renderer can avoid asking
 * the optimizer to upscale.
 *
 * Not in CI, and deliberately not at request time: it is a handful of numbers
 * that change only when a post does, and the alternative is probing every
 * image on every ISR revalidation. Forgetting to run it is cheap - a missing
 * entry costs the image its dimensions, nothing else.
 *
 * The map is keyed by source URL, which is also where these images' attribution
 * lives: they are event photography by other people, and the key is the
 * pointer back to whose.
 *
 * Uses `fetchRawPosts`, not `fetchPosts`: `fetchPosts` returns `body` already
 * rendered to HTML by `renderPostBody`, and `selectImageUrls` expects markdown
 * link syntax (`![alt](url)`), which no longer exists once an image has become
 * an `<img>` tag. `fetchRawPosts` returns the pre-render markdown body instead.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { fetchRawPosts, isOptimizableImageUrl, selectImageUrls } from "@patorsiang/content/posts";
import { imageSize } from "image-size";

const mapPath = join(import.meta.dir, "../src/lib/post-image-sizes.ts");
const prettierBin = join(import.meta.dir, "../../../node_modules/.bin/prettier");

async function measure(url: string): Promise<readonly [number, number] | null> {
  const response = await fetch(url);

  if (!response.ok) {
    console.warn(`skipped ${url}: ${response.status}`);
    return null;
  }

  // response.ok alone doesn't catch a 200 that is actually an HTML error page
  // from some intermediate proxy, and image-size would then report the
  // dimensions of nothing at all.
  const contentType = response.headers.get("content-type");

  if (!contentType?.split(";")[0].trim().startsWith("image/")) {
    console.warn(`skipped ${url}: response was not an image (content-type: ${contentType})`);
    return null;
  }

  try {
    const { width, height } = imageSize(new Uint8Array(await response.arrayBuffer()));

    return [width, height] as const;
  } catch (error) {
    console.warn(`skipped ${url}: could not read dimensions (${String(error)})`);
    return null;
  }
}

async function main() {
  // Raw markdown, not rendered HTML: selectImageUrls reads markdown syntax.
  const posts = await fetchRawPosts();
  const entries: [string, readonly [number, number]][] = [];

  for (const post of posts) {
    for (const url of selectImageUrls(post.body)) {
      // Anything off the allowlist renders as a link, never as an <img>, so
      // its dimensions would be recorded for a tag that is never emitted.
      if (!isOptimizableImageUrl(url)) {
        console.warn(`skipped ${url}: host is not in POST_IMAGE_SOURCES`);
        continue;
      }

      const size = await measure(url);

      if (!size) continue;

      entries.push([url, size]);
      console.log(`measured ${url} -> ${size[0]}x${size[1]}`);
    }
  }

  const literal = entries
    .map(([url, [width, height]]) => `  [${JSON.stringify(url)}, [${width}, ${height}]],`)
    .join("\n");

  writeFileSync(
    mapPath,
    `/* Generated by scripts/post-image-manifest.ts. Do not edit by hand. */\n` +
      `export const POST_IMAGE_SIZES: ReadonlyMap<string, readonly [number, number]> = new Map([\n` +
      `${literal}\n]);\n`,
    "utf8",
  );

  // The output is committed source, so `format:check` gates it - and whether
  // an entry fits on one line depends on how long a post's image URLs happen
  // to be. Emitting Prettier's own shape is guesswork; running Prettier is
  // not. Without this, the first post with long image URLs fails CI on
  // formatting, which is a confusing way to be told an image was measured.
  //
  // The workspace-root binary directly, not `bunx`: prettier is a root
  // devDependency with no entry in this app's node_modules/.bin, and bunx
  // resolving a name it cannot find locally reaches for the network and can
  // sit there indefinitely. This path either exists or fails immediately.
  const formatted = Bun.spawnSync([prettierBin, "--write", mapPath], { stdout: "ignore" });

  if (formatted.exitCode !== 0) {
    throw new Error(`prettier failed on ${mapPath}: ${formatted.stderr.toString()}`);
  }

  console.log(`wrote ${mapPath}`);
}

await main();
