/**
 * Downloads every remote image referenced by a post into public/posts/<slug>/
 * and writes the URL-to-path map the renderer uses.
 *
 * Run by hand when a post gains an image:
 *   bun run --cwd apps/portfolio-web vendor:post-images
 *
 * Not in CI, and not at request time: ISR runs on a read-only filesystem and
 * cannot write to public/. Between deploys an unvendored image renders as a
 * link, which is why the renderer degrades rather than emitting a broken img.
 *
 * These images are event photography by other people. Each keeps its source
 * URL in sources.json so attribution stays recoverable.
 *
 * Uses `fetchRawPosts`, not `fetchPosts`: `fetchPosts` returns `body` already
 * rendered to HTML by `renderPostBody`, and `selectImageUrls` expects
 * markdown link syntax (`![alt](url)`), which no longer exists once an image
 * has become an `<img>` (or, unvendored, an `<a>`) tag. `fetchRawPosts`
 * returns the pre-render markdown body instead.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { fetchRawPosts, selectImageUrls } from "@patorsiang/content/posts";

const publicDir = join(import.meta.dir, "../public/posts");
const mapPath = join(import.meta.dir, "../src/lib/vendored-images.ts");
const prettierBin = join(import.meta.dir, "../../../node_modules/.bin/prettier");

const EXTENSION_BY_CONTENT_TYPE: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/svg+xml": "svg",
};

const extensionFromUrl = (url: string) => {
  const path = new URL(url).pathname;
  const match = /\.(png|jpe?g|webp|gif|svg)$/i.exec(path);

  return match ? match[1].toLowerCase() : null;
};

/**
 * Cloudinary and similar serve extensionless transform URLs, so the URL
 * alone is not always enough. Content-Type is the actual authority on what
 * was downloaded; webp is the fallback only when neither the URL nor a
 * recognised image content-type says otherwise.
 */
const extensionOf = (url: string, contentType: string | null) =>
  extensionFromUrl(url) ??
  (contentType && EXTENSION_BY_CONTENT_TYPE[contentType.split(";")[0].trim()]) ??
  "webp";

async function main() {
  // Raw markdown, not rendered HTML: selectImageUrls reads markdown syntax.
  const posts = await fetchRawPosts();
  const entries: [string, string][] = [];

  for (const post of posts) {
    const urls = selectImageUrls(post.body);
    if (urls.length === 0) continue;

    const dir = join(publicDir, post.slug);
    mkdirSync(dir, { recursive: true });

    const sources: Record<string, string> = {};

    for (const [index, url] of urls.entries()) {
      const response = await fetch(url);

      if (!response.ok) {
        console.warn(`skipped ${url}: ${response.status}`);
        continue;
      }

      // response.ok alone doesn't catch a 200 that's actually an HTML error
      // page from some intermediate proxy - a vendored file that 404s or
      // contains an HTML error page still satisfies a same-origin check.
      const contentType = response.headers.get("content-type");

      if (!contentType?.split(";")[0].trim().startsWith("image/")) {
        console.warn(`skipped ${url}: response was not an image (content-type: ${contentType})`);
        continue;
      }

      const name = `image-${index + 1}.${extensionOf(url, contentType)}`;

      writeFileSync(join(dir, name), Buffer.from(await response.arrayBuffer()));
      sources[name] = url;
      entries.push([url, `/posts/${post.slug}/${name}`]);
      console.log(`vendored ${url} -> /posts/${post.slug}/${name}`);
    }

    writeFileSync(join(dir, "sources.json"), `${JSON.stringify(sources, null, 2)}\n`, "utf8");
  }

  const literal = entries
    .map(([url, path]) => `  [${JSON.stringify(url)}, ${JSON.stringify(path)}],`)
    .join("\n");

  writeFileSync(
    mapPath,
    `/* Generated by scripts/vendor-post-images.ts. Do not edit by hand. */\n` +
      `export const VENDORED_IMAGES: ReadonlyMap<string, string> = new Map([\n${literal}\n]);\n`,
    "utf8",
  );

  // The output is committed source, so `format:check` gates it - and whether
  // an entry fits on one line depends on how long a post's image URLs happen
  // to be. Emitting Prettier's own shape is guesswork; running Prettier is
  // not. Without this, the first post with long image URLs fails CI on
  // formatting, which is a confusing way to be told an image was vendored.
  //
  // The workspace-root binary directly, not `bunx`: prettier is a root
  // devDependency with no entry in this app's node_modules/.bin, and bunx
  // resolving a name it cannot find locally reaches for the network and can
  // sit there indefinitely. This path either exists or fails immediately.
  const formatted = Bun.spawnSync([prettierBin, "--write", mapPath], { stdout: "ignore" });

  if (formatted.exitCode !== 0) {
    throw new Error(`prettier failed on ${mapPath}: ${formatted.stderr.toString()}`);
  }

  console.log(`wrote ${mapPath}`);
}

await main();
