/* Generated by scripts/post-image-manifest.ts. Do not edit by hand. */
export const POST_IMAGE_SIZES: ReadonlyMap<string, readonly [number, number]> = new Map([
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-hero.jpg",
    [1600, 1194],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-nano-pro.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-gpt-image-2.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-seedream-5-lite.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-thai-nano-pro.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-thai-seedream-4.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-thai-seedream-5-lite.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-render-v1.jpg",
    [1600, 1600],
  ],
  [
    "https://raw.githubusercontent.com/patorsiang/thinking-in-public/main/assets/aipass-showroom-veo-poster.jpg",
    [1280, 720],
  ],
  [
    "https://p-u.popcdn.net/event_details/posters/000/139/651/large/a997f2de6097d60ead51f4319cadbeb3741a03a9.png?1773125360",
    [800, 1132],
  ],
  [
    "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_1080,q_100,w_1080/v1/gcs/platform-data-goog/events/blob_o3IC4RX",
    [2160, 2160],
  ],
]);
